#配置数据源
spring:
  datasource:
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/aaa_service?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #Druid
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化配置
      initial-size: 3
      # 最小连接数
      min-idle: 3
      # 最大连接数
      max-active: 15
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 90000
      # 最大空闲时间
      min-evictable-idle-time-millis: 1800000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      validation-query: select 1
      # 配置监控统计拦截的filters
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false

      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

  #配置 Jpa
  jpa:
    hibernate:
      # 生产环境设置成 none，避免程序运行时自动更新数据库结构
      ddl-auto: none
#  flyway:
#    locations: classpath:/db
#    baseline-version: 2
#    baseline-on-migrate: true
#    placeholder-replacement: false
  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 100MB
      max-request-size: 200MB
  redis:
    #数据库索引
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    #连接超时时间
    timeout: 5000
#jwt
jwt:
  header: Authorization
  secret: mySecret
  # token 过期时间/毫秒，6小时  1小时 = 3600000 毫秒
  expiration: 21600000
  # 在线用户key
  online: online-token
  # 验证码
  codeKey: code-key

#是否允许生成代码，生产环境设置为false
generator:
  enabled: true

#是否开启 swagger-ui
swagger:
  enabled: true

# 文件存储路径(相对路径)
file:
  path: system/file
  avatar: system/avatar
  upload: upload
  # 文件大小 /M
  maxSize: 100
  avatarMaxSize: 5
